### PR TITLE
Add MD-UV3x0 Plus target

### PR DESCRIPTION
**Pull request by marcoSchr**
This will add a target for the MD-UV3x0 Plus.

The plus version is the same as the non plus version, just with two pins swapped.
Therefor only a define for the plus is added and checked in the pinmap in order to flip the two pins.

### CODE REVIEW

**Comment by silseva** [comment]
Thank you!
Just one thing: it would be interesting to compare the content of the radio's external flash security register at address 0x3000 with the one of a "plain" UV380. Probably this small hardware difference is codified in somewhere.

**Comment by lemielek** [comment]
RT3S als6?
How to do that?

**Comment by silseva** [comment]
The retevis RT3s is already supported by the `mduv3x0` target, the hardware is identical

**Comment by silseva** [comment]
@marcoSchr should I merge the PR or we want to wait until also the GPS issue gets fixed?

**Comment by marcoSchr** [comment]
We can merge it now in its own branch.
This should make it easier for others to test it and maybe find other issues beside the GPS and memory.

**Comment by silseva** [comment]
Merged, thank you!

**Pull request merged**
