### PR TITLE
Scrollbar

### LINKED ISSUE #167: Feature: Scrollbar for menus
When scrolling up and down in the menu, there is no indication where in the list we are.

To improve this we would need a scrollbar to show the position in the menu.
The current menu has enough space on the right side to add a scrollbar.

I see the following requirements for this:
- The scrollbar is shown when there is more content, than can be shown on the screen
- The scrollbar should only move, when the shown content moves

### PR DESCRIPTION
**Pull request by marcoSchr**
This Pull request will add a scrollbar to menus.
The scrollbar will only appear if there are more entries than fit on the screen.
The scrollbars size is adjusted by the number of entries in the menu.

This is currently only implemented for the default UI, not yet for the module17.

This also changes the scrolling logic, by calling the scroll function once, instead of separate for each menu, as we now store the length of each menu an array.

This will fix #167

### CODE REVIEW

**Comment by silseva** [comment]
Is this PR still a WIP or can be merged?

**Comment by marcoSchr** [comment]
> Is this PR still a WIP or can be merged?

Yes it is still WIP. I want to see, if I can rebase [feat_menu_wrap](https://github.com/OpenRTX/OpenRTX/tree/feat_menu_wrap) onto master and then rebase this onto it. 
This will allow to have scrollbars in the Channels/Contacts/Banks menus.

**Comment by marcoSchr** [comment]
I have now included the feat_menu_wrap branch changes and updated it on top of the latest master branch.

**Comment by silseva** [comment]
Hi!
Thanks for your work! Unfortunately I cannot merge this into master now because I found an issue with the code counting the number of channels, banks and contacts: since the SPI transfer is not very fast, when you have a radio with a codeplug with a lot of elements it takes _minutes_ to boot because it has to go through all the elements. If you agree, I'll merge this PR into a feature branch and then integrate it into master when we switch to the OpenRTX codeplug, which has the number of banks/channels/contacts in the CPS header and does not require enumerating all the elements to count them.

**Comment by marcoSchr** [comment]
You can merge this into a feature branch.

**Comment by silseva** [comment]
Thanks!

**Pull request merged**
